{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "node-feature-discovery.saName" . }}
  labels:
{{ include "node-feature-discovery.labels" . | indent 4 }}
{{- end }}
---
{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "node-feature-discovery.fullname" . }}
  labels:
{{ include "node-feature-discovery.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "node-feature-discovery.fullname" . }}
  labels:
{{ include "node-feature-discovery.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "node-feature-discovery.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "node-feature-discovery.saName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
