---
- name: Clone CommsPowerManagement repository
  git: 
    repo: "{{ sstbf_git_url }}"
    dest: "{{ sstbf_dir }}"
    force: yes
  when: sst_bf_configuration_enabled

- name: copy scripts to /usr/local/bin
  copy:
    src: "{{ sstbf_dir }}/sst-bf.py"
    dest: "/usr/local/bin/sst-bf.py"
    mode: 0755
    remote_src: yes
  when: sst_bf_configuration_enabled
  
- name: configure CPU on node
  command: sst-bf.py -{{ sst_bf_mode }} 
  when: sst_bf_configuration_enabled
