---
- name: install dependencies
  include_role:
    name: install-dependencies

- name: clone Bond cni repository
  git:
    repo: "{{ bond_cni_git_url }}"
    dest: "{{ bond_cni_dir }}"
    version: "{{ bond_cni_version }}"
    force: yes

- name: build Bond CNI
  command: sh build.sh
  args:
    chdir: "{{ bond_cni_dir }}"

- name: create /opt/cni/bin
  file:
   path: "/opt/cni/bin"
   state: directory
   recurse: yes

- name: install Bond cni binary to /opt/cni/bin directory
  copy:
    src: "{{ bond_cni_path }}"
    dest: "/opt/cni/bin/bond"
    mode: 0755
    remote_src: yes