- hosts: k8s-cluster
  tasks: []
  roles:
    - { role: cluster-defaults }
    - { role: k8s-all-preconfigure }
  environment: "{{ proxy_env | d({}) }}"
  any_errors_fatal: true

- hosts: kube-node
  tasks: []
  roles:
    - { role: cluster-defaults }
    - { role: k8s-node-preconfigure }
    - role: sst-bf-configure
      when: sst_bf_configuration_enabled | default(true)
      tags: sst-bf
  environment: "{{ proxy_env | d({}) }}"
  any_errors_fatal: true
