{{- if .Values.taspolicy.create }}
apiVersion: telemetry.intel.com/v1alpha1
kind: TASPolicy
metadata:
  name: {{ include "telemetry-aware-scheduling.fullname" . }}-scheduling-policy
  namespace: {{ .Values.namespace }} 
spec:
  strategies:
    {{- if .Values.taspolicy.deschedule.enabled }}
    deschedule:
      rules:
      {{- range .Values.taspolicy.deschedule.rules }}
      - metricname: {{ .name }}
        operator: {{ .operator }}
        target: {{ .target }}
      {{- end }}
    {{- end }}
    {{- if .Values.taspolicy.dontschedule.enabled }}
    dontschedule:
      rules:
      {{- range .Values.taspolicy.dontschedule.rules }}
      - metricname: {{ .name }}
        operator: {{ .operator }}
        target: {{ .target }}
      {{- end }}
    {{- end }}
    {{- if .Values.taspolicy.scheduleonmetric.enabled }}
    scheduleonmetric:
      rules:
      - metricname: {{ .Values.taspolicy.scheduleonmetric.rules.name }}
        operator: {{ .Values.taspolicy.scheduleonmetric.rules.operator }}
    {{- end }}
{{- end }} 