---
- name: check if namespace exists
  command: kubectl get namespace {{ prometheus_namespace }}
  register: ns_exists
  failed_when: no
  when: inventory_hostname == groups['kube-master'][0]

- name: create a namespace
  command: kubectl create namespace {{ prometheus_namespace }}
  when: inventory_hostname == groups['kube-master'][0] and "NotFound" in ns_exists.stderr

- name: populate Prometheus Helm chart values template and push to master node
  template:
    src: "prometheus-values.yml.j2"
    dest: "/usr/src/charts/prometheus-values.yml"
    force: yes
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: install Prometheus Helm chart
  command: helm upgrade --install --namespace {{ prometheus_namespace }} {{ prometheus_name }} -f prometheus-values.yml stable/prometheus
  args:
    chdir: "/usr/src/charts/"
  when:
    - inventory_hostname == groups['kube-master'][0]

