---
- set_fact:
    temp_ddp_path: "{{ tmp_placeholder }}/{{ pkgurl | regex_replace('^https?://.*/(.*).zip$', '\\1') }}"

- name: Create temp placeholder for each DDP package
  become: yes
  file:
    path: "{{ temp_ddp_path }}"
    state: directory
    mode: 0700
    owner: root
    group: root

- name: Download and unarchive DDP packages from list of URLs
  unarchive:
    src: "{{ pkgurl  }}"
    dest: "{{ temp_ddp_path }}"
    remote_src: yes
- name: Find PKG files
  find:
    paths: "{{ temp_ddp_path }}"
    patterns: '*.pkgo,*.pkg'
    file_type: file
    recurse: yes
  register: pkgfiles

- name: Copy DDP packages into installation directory
  copy:
    src: "{{ pkgfile.path  }}"
    dest: "{{ install_dir  }}"
    remote_src: yes
  loop: "{{ pkgfiles.files }}"
  loop_control:
    loop_var: pkgfile
