---
- name: Create DDP package installation directory
  become: yes
  file:
    path: "{{ install_dir }}"
    state: directory
    mode: 0700
    owner: root
    group: root

- name : install ddp package from a URL
  include: install_a_pkg.yml
  loop: "{{ pkgurls }}"
  loop_control:
    loop_var: pkgurl


