---
sriov_net_dp_git_url: "https://github.com/intel/sriov-network-device-plugin.git"
sriov_net_dp_git_ref: "v3.1"
sriov_net_dp_dir: "/usr/src/sriov-network-device-plugin"
sriov_net_dp_build_image_locally: true
sriov_net_dp_autogenerate: true
sriov_net_dp_namespace: kube-system


registry_local_address: "localhost:5000"
sriovdp_config_data: |
    {
        "resourceList": [{
                "resourceName": "intel_sriov_netdevice",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["154c", "10ed"],
                    "drivers": ["iavf", "i40evf", "ixgbevf"]
                }
            },
            {
                "resourceName": "intel_sriov_dpdk",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["154c", "10ed"],
                    "drivers": ["vfio-pci"]
                }
            }
        ]
    }

