---
- name: assert that Multus is enabled in the config
  assert:
    that:
      - "kube_network_plugin_multus"
    fail_msg: "Multus must be enabled to have fully functional cluster deployment"

- name: assert that Helm is enabled in the config
  assert:
    that:
      - "helm_enabled"
    fail_msg: "Helm must be enabled to have fully functional cluster deployment"

- name: assert that Docker registry is enabled in the config
  assert:
    that:
      - "registry_enabled"
    fail_msg: "Docker registry must be enabled to have fully functional cluster deployment"

- name: install kubespray python requirements
  pip:
    requirements: "{{ role_path }}/files/requirements.txt"
